### ISSUE TITLE
incompatible changes when defining a policy

### ISSUE THREAD

**Issue by mariux** [terraform-aws-modules/terraform-aws-s3-bucket#13]
just a small heads up:

When releasing newer minor versions the last days, you added incompatible changes:

in 1.0.0 we had defined `policy = ....` which created a bucket policy ... when using the latest the bucket policy is not created anymore even if set and you have to define the policy and add an `attach_policy = true` attribute.

maybe a good idea to assume you want to attach a policy if you define a policy (not `null` or `""`)?

thanks a lot.

**Comment by antonbabenko** [comment]
Marius,

My bad that this was not introduced in the first release of this module.

Unfortunately, this was not possible to do as you suggest because of a limitation in Terraform which says `value of 'count' cannot be computed`. There are several related issues in Terraform core, for eg, https://github.com/hashicorp/terraform/issues/13980 .

Before this is 100% fixed in Terraform, we can't do anything better than requiring users to set `attach_policy = true` together with the `policy`.

Closing this issue.

Thank you!

**Comment by mariux** [comment]
still an incompatible change that crashes when relying on semantic versioning.. which can be fixed by increasing version number as this reflects a breaking change.
