### ISSUE TITLE
Fix CHANGELOG.md markdown

### ISSUE THREAD

**Issue by maunzCache** [terraform-aws-modules/terraform-aws-s3-bucket#130]
## Is your request related to a new offering from AWS?
Nope, not at all.

## Is your request related to a problem? Please describe.
The markdown of the changelog file is a bit messed up.

## Describe the solution you'd like.
The headline "Changelog" is included twice and some versions have mixed up header sizes as well. Also since 2.11.1 versioning scheme has been changed which drops the "v" prefix. I guess this is not correctly documented as the actual tag still contain that character.

Edit: Oh version 2.3.0 has no changelog at all. Or that is written with magic ink and i cannot get my display to show it.

## Describe alternatives you've considered.
Ignoring it but i really cannot :(

## Additional context
Include markdownlinter in pre-commit hook

**Comment by antonbabenko** [comment]
Thanks for reporting this issue. It is weird that the problem is only in this repository and not in [VPC module](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/CHANGELOG.md), for example.

/cc @bryantbiggs Do you have any ideas why https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/CHANGELOG.md looks broken?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.14.0 :tada:
