### ISSUE TITLE
How to set "ignore_changes" lifecycle rule?

### ISSUE THREAD

**Issue by ghost** [terraform-aws-modules/terraform-aws-s3-bucket#21]
Hello,

I am trying this module as a replacement for different S3 resources I created manually so far
One use-case I have for a static website is to [ignore changes](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) on website.routing_rules.

I can write that lifecycle rule on the resource:

```
resource "aws_s3_bucket" "website" {
  # ...
  website {
    index_document = "index.html"
    error_document = "404.html"
  }

  # ...
  lifecycle {
    ignore_changes = [
      website.0.routing_rules
    ]
  }
}
```

But I cannot figure out how to migrate that lifecycle pattern to the module?

When I try:

```
module "website" {
  source = "terraform-aws-modules/s3-bucket/aws"

  # ...
  website = {
    index_document = "index.html"
    error_document = "404.html"
  }

  # ...
  lifecycle_rule = [
    {
      ignore_changes = [
        website.0.routing_rules
      ]
    }
  ]
}
```

I see the following error:

> A reference to a resource type must be followed by at least one attribute
> access, specifying the resource name.

Not very self-explanatory, but from some research, it seems difficult today to inject ignore_change lifecycle rules to modules since [variables are not supported](https://github.com/hashicorp/terraform/issues/3116).

Unless someone knows a magic trick?

**Comment by chancez** [comment]
@flosch-hb Your only hope is to fork/vendor the module with your lifecycle change in it, or hope that Hashicorp removes this restriction at some point in the future.

**Comment by boldandbusted** [comment]
Just to put a fine point on @chancez comment: This difficulty is known by the Terraform core team, and they have been tracking this since 2015 here: https://github.com/hashicorp/terraform/issues/3116 and there is a proposal (also started in 2015) to start addressing the fundamental Terraform architecture challenges here: https://github.com/hashicorp/terraform/issues/4149. 

I also have used the approach @chancez described - creating individual forks that contain the explicit, hardcoded lifecycle changes. It's very ugly to have to do this, and only reasonably manageable when you have a small group of lifecycle changes (like two, max). Lord help you if you have a matrix of changes needed for your particular use case. :/ Cheers.

**Comment by bryantbiggs** [comment]
as @chancez  and @boldandbusted  pointed out - this is something we really, really hope lands in Terraform soon as this is probably one of the most requested changes within these modules. unfortunately, there isn't a lot we can do until that support arrives from Terraform directly
