### ISSUE TITLE
example for BucketOwnerEnforced (disabled ACLs)

### ISSUE THREAD

**Issue by marekaf** [terraform-aws-modules/terraform-aws-s3-bucket#250]
## Is your request related to a problem? Please describe.

Hi. I think it is not clear on how to create an S3 bucket with ACLs disabled (BucketOwnerEnforced, acl not set).

Creating a bucket with `object_ownership = "BucketOwnerEnforced"` and `acl = "private"` will fail. It is not clear enough from the README as why this is wrong.

## Describe the solution you'd like.

Is it possible to provide a working example in `examples/complete` perhaps? Also to mention what and if `acl` variable should be set to. 

Thanks!

**Comment by antonbabenko** [comment]
`object_ownership = "BucketOwnerEnforced"` and `acl = "private"` will fail because this is an invalid combination of parameters according to the behavior of Amazon S3 ([read the docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html)).

Please take a look into `examples/complete` - there are various combinations of the values shown.

**Comment by marekaf** [comment]
In examples/complete there's not even a single example of BucketOwnerEnforced. That's what I'm requesting in this Issue.

I mentioned that I know that this combination is invalid (because I "read the docs") but the docs of this module don't make that obvious for somebody who doesn't know s3 as much.
